using Gehtsoft.PDFFlow.Builder;
using Gehtsoft.PDFFlow.Models.Enumerations;
using Gehtsoft.PDFFlow.Models.Shared;
using LabResults.Model;
using Newtonsoft.Json;
using System.IO;
using static LabResults.LabResultsBuilder;

namespace LabResults
{
    internal class LabResultsHeaderBuilder
    {
        PatientDetailsData patientDetailsData = JsonConvert.DeserializeObject<PatientDetailsData>
            (File.ReadAllText(Path.Combine("Content", "patient-details.json")));
        SpecimenDetailsData specimenDetailsData = JsonConvert.DeserializeObject<SpecimenDetailsData>
            (File.ReadAllText(Path.Combine("Content", "specimen-details.json")));
        PhysicianDetailsData physicianDetailsData = JsonConvert.DeserializeObject<PhysicianDetailsData>
            (File.ReadAllText(Path.Combine("Content", "physician-details.json")));
        TestInfoData testInfoData = JsonConvert.DeserializeObject<TestInfoData>
            (File.ReadAllText(Path.Combine("Content", "test-info.json")));
        SpecimenInfoData specimenInfoData = JsonConvert.DeserializeObject<SpecimenInfoData>
            (File.ReadAllText(Path.Combine("Content", "specimen-info.json")));

        string logoPath = Path.Combine("images", "LabResults_Logo.png");
        string codePath = Path.Combine("images", "LabResults_Code.png");

        internal void Build(SectionBuilder sectionBuilder)
        {
            var styleParagraph1 = StyleBuilder.New().SetLineSpacing(1)
                                .SetFont(FNT9B).SetFontColor(blueGreen);

            var styleParagraph2 = StyleBuilder.New().SetLineSpacing(0.5f)
                                .SetFont(FNT9B).SetFontColor(blueGreen);

            sectionBuilder
                .AddTable()
                    .SetBorderStroke(Stroke.None)
                    .SetWidth(XUnit.FromPercent(100))
                    .AddColumnPercentToTable("", 50)
                    .AddColumnPercentToTable("", 50)
                    .AddRow()
                        .AddCell()
                            .SetPadding(0, 0, 0, 1)
                            .AddImageToCell(logoPath, 210, 37, ScalingMode.UserDefined)
                    .ToRow()
                        .AddCell()
                            .SetPadding(5, 8, 0, 0)
                            .AddParagraph(testInfoData.Report)
                                .SetFont(FNT10B)
            .ToSection()
                .AddLineToSection(PageWidth, 2)
                .AddTable()
                    .SetBorderStroke(Stroke.None)
                    .SetWidth(XUnit.FromPercent(100))
                    .AddColumnPercentToTable("", 50)
                    .AddColumnPercentToTable("", 50)
                    .AddRow()
                        .AddCell()
                            .SetFont(FNT9B)
                            .SetFontColor(blueGreen)
                            .AddParagraph("Specimen ID:")
                                .SetMarginTop(2)
                                .AddTabSymbol()
                                .AddTabulationInPercent(25)
                                .AddText(specimenInfoData.SpecimenID)
                                    .SetFont(FNT9)
                         .ToCell()
                            .AddParagraph("Control ID:")
                                .SetMarginTop(2)
                                .AddTabSymbol()
                                .AddTabulationInPercent(25)
                                .AddText(specimenInfoData.ControlID)
                                    .SetFont(FNT9)
                         .ToCell()
                            .AddParagraph("Acct #:")
                                .SetMarginTop(0.5f)
                                .AddTabSymbol()
                                .AddTabulationInPercent(25)
                                .AddText(specimenInfoData.Acct)
                                    .SetFont(FNT9)
                         .ToCell()
                            .AddParagraph("Phone:")
                                .SetMarginTop(0.5f)
                                .AddTabSymbol()
                                .AddTabulationInPercent(25)
                                .AddText(specimenInfoData.Phone)
                                    .SetFont(FNT9)
                         .ToCell()
                            .AddParagraph("Rte:")
                                .SetMarginTop(0.5f)
                                .AddTabSymbol()
                                .AddTabulationInPercent(25)
                                .AddText(specimenInfoData.Rte)
                                    .SetFont(FNT9)
                    .ToRow()
                        .AddCell()
                            .SetPadding(5, 2, 0, 0)
                            .SetFont(FNT9)
                            .AddParagraphToCell(testInfoData.Master)
                            .AddParagraphToCell(testInfoData.Account)
                            .AddParagraphToCell(testInfoData.Address1)
                            .AddParagraphToCell(testInfoData.Address2)
                            .AddImage(codePath)
                                .SetMarginTop(12)
            .ToSection()
                .AddTable()
                    .SetMarginTop(15)
                    .SetBorderWidth(0.5f, 0, 0, 0)
                    .SetWidth(XUnit.FromPercent(100))
                    .AddColumnPercentToTable("", 31)
                    .AddColumnPercentToTable("", 32)
                    .AddColumnPercentToTable("", 37)
                    .AddRow()
                        .SetFont(FNT10B)
                        .AddCell()
                            .SetPadding(12, 0, 0, 0)
                            .AddParagraph("Patient Details")
                                .SetLineSpacing(1)
                        .ToCell()
                            .AddParagraph("DOB:")
                                .ApplyStyle(styleParagraph1)
                                .AddTabSymbol()
                                .AddTabulationInPercent(44)
                                .AddText(patientDetailsData.DOB)
                                    .SetFont(FNT9)
                        .ToCell()
                            .AddParagraph("Age(y/m/d)")
                                .ApplyStyle(styleParagraph1)
                                .AddTabSymbol()
                                .AddTabulationInPercent(44)
                                .AddText(patientDetailsData.Age)
                                    .SetFont(FNT9)
                        .ToCell()
                            .AddParagraph("Gender:")
                                .ApplyStyle(styleParagraph1)
                                .AddTabSymbol()
                                .AddTabulationInPercent(44)
                                .AddText(patientDetailsData.Gender)
                                    .SetFont(FNT9)
                        .ToCell()
                            .AddParagraph("Patient ID:")
                                .ApplyStyle(styleParagraph2)
                                .AddTabSymbol()
                                .AddTabulationInPercent(44)
                                .AddText(patientDetailsData.PatientID)
                                    .SetFont(FNT9)
                    .ToRow()
                        .SetFont(FNT10B)
                        .AddCell()
                            .SetPadding(12, 0, 0, 0)
                            .AddParagraph("Specimen Details")
                                .SetLineSpacing(1)
                        .ToCell()
                            .AddParagraph("Date collected:")
                                .ApplyStyle(styleParagraph1)
                                .AddTabSymbol()
                                .AddTabulationInPercent(44)
                                .AddText(specimenDetailsData.Collected)
                                    .SetFont(FNT9)
                        .ToCell()
                            .AddParagraph("Date received:")
                                .ApplyStyle(styleParagraph1)
                                .AddTabSymbol()
                                .AddTabulationInPercent(44)
                                .AddText(specimenDetailsData.Received)
                                    .SetFont(FNT9)
                        .ToCell()
                            .AddParagraph("Date entered:")
                                .ApplyStyle(styleParagraph1)
                                .AddTabSymbol()
                                .AddTabulationInPercent(44)
                                .AddText(specimenDetailsData.Entered)
                                    .SetFont(FNT9)
                        .ToCell()
                            .AddParagraph("Date reported:")
                                .ApplyStyle(styleParagraph2)
                                .AddTabSymbol()
                                .AddTabulationInPercent(44)
                                .AddText(specimenDetailsData.Reported)
                                    .SetFont(FNT9)
                    .ToRow()
                        .SetFont(FNT10B)
                        .AddCell()
                            .SetPadding(12, 0, 0, 0)
                            .AddParagraph("Physician Details")
                                .SetLineSpacing(1)
                        .ToCell()
                            .AddParagraph("Ordering:")
                                .ApplyStyle(styleParagraph1)
                                .AddTabSymbol()
                                .AddTabulationInPercent(44)
                                .AddText(physicianDetailsData.Ordering)
                                    .SetFont(FNT9)
                        .ToCell()
                            .AddParagraph("Referring:")
                                .ApplyStyle(styleParagraph1)
                                .AddTabSymbol()
                                .AddTabulationInPercent(44)
                                .AddText(physicianDetailsData.Referring)
                                    .SetFont(FNT9)
                        .ToCell()
                            .AddParagraph("ID:")
                                .ApplyStyle(styleParagraph1)
                                .AddTabSymbol()
                                .AddTabulationInPercent(44)
                                .AddText(physicianDetailsData.ID)
                                    .SetFont(FNT9)
                        .ToCell()
                            .AddParagraph("NPI:")
                                .ApplyStyle(styleParagraph2)
                                .AddTabSymbol()
                                .AddTabulationInPercent(44)
                                .AddText(physicianDetailsData.NPI)
                                    .SetFont(FNT9)
                .ToSection()
                    .AddLine(PageWidth, 1, Stroke.Solid, blueGreen)
                        .SetMarginTop(5);
        }
    }
}